baseURL = 'https://posy.ovh/'
languageCode = "pl-pl"
DefaultContentLanguage = "pl"
title = 'POSy.ovh'
theme = 'hugo-theme-techdoc'
[params]
    description = "by Michał_32 ©2024"
    title = "POSy.ovh"
    custom_font_color = "#000000"
    custom_background_color = "#FF0000"
    menu_style = "slide-menu"
    dateformat = "2 Jan 2006"